[build-system]
requires = [
  "setuptools>=68",
  "wheel",
  "Cython>=0.29",
  "numpy>=1.22",
]
build-backend = "setuptools.build_meta"

[project]
name = "vision-engine"
version = "0.1.1"
description = "Ultra-fast AprilTag detector bindings for edge robotics implemented in Cython"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "numpy>=1.22",
]
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: C",
  "Programming Language :: Python :: Implementation :: CPython",
  "Operating System :: OS Independent",
]

[tool.setuptools]
include-package-data = true
packages = []
py-modules = []

[tool.cibuildwheel]
build = "cp310-* cp311-* cp312-*"
skip = "pp* *-musllinux_*"
archs = "x86_64 aarch64"
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"
